all: main.c read_input_files.c linked_list_functions.c print_functions.c basic_functions.c container_functions.c
	gcc -std=c99 -Wall -O3 -o main main.c read_input_files.c linked_list_functions.c print_functions.c basic_functions.c container_functions.c -I. -lm

clean:
	rm *.o
